title = "Abhemanyu Sarin"
description = "Software Engineer"
base_url = "https://abhemanyus.github.io"
compile_sass = true
highlight_code = true
build_search_index = false
generate_feed = true
highlight_theme = "base16-ocean-light"
theme = "anatole-zola"
default_language = "en"

[markdown]
external_links_target_blank = true
external_links_no_referrer = true
external_links_no_follow = true
render_emoji = true
highlight_code = true
smart_punctuation = true
highlight_theme = "base16-ocean-light"

taxonomies = [
    {name = "tags"},
]

[languages.en]
title = "Abhemanyu Sarin"
description = "Software Engineer"
generate_feed = true
taxonomies = [
    {name = "tags"},
]

[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

[extra.social]
github = "abhemanyus"
twitter = "abhemanyus"
linkedin = "abhemanyu-sarin-82b677211"

[extra.show]
tags = true
links = true
