title = "Abhemanyu Sarin"
description = "Software Engineer"
base_url = "https://abhemanyus.github.io"
compile_sass = true
build_search_index = true
generate_feed = true
theme = "hephaestus"
default_language = "en"

[markdown]
external_links_target_blank = true
external_links_no_referrer = true
external_links_no_follow = true
render_emoji = true
highlight_code = true
smart_punctuation = true
highlight_theme = "base16-ocean-light"

[extra.show]
tags = true
links = true

[extra]
bundled = "true"
author = "Abhemanyu Sarin"
about = "A software engineer"

menu = [
{ text = "Home", link = "/" },
{ text = "About", link = "/about/" },
{ text = "Education", link = "/education" },
{ text = "Skills", link = "/skills/" },
{ text = "Projects", link = "/projects/"}
]

social = [
{ user = "Abhemanyu Sarin", link = "mailto:abhemanys@gmail.com", icon = "mail-outline"},
]